name: ChessHub
description: Ajedrez.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^5.2.0
  cupertino_icons: ^1.0.6
  go_router: ^13.0.0
  logging: ^1.2.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  socket_io_client: ^2.0.3+1
  http: ^1.2.1
  flutter_svg: ^2.0.10+1
  google_fonts: 6.2.0
  smooth_page_indicator: 1.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  test: ^1.24.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/images_pase/boards/
    - assets/images/images_pase/pieces/alpha/
    - assets/images/images_pase/pieces/anarcandy/
    - assets/images/images_pase/pieces/cardinal/
    - assets/images/images_pase/pieces/cburnett/
    - assets/images/images_pase/pieces/celtic/
    - assets/images/images_pase/pieces/chess7/
    - assets/images/images_pase/pieces/chessnut/
    - assets/images/images_pase/pieces/companion/
    - assets/images/images_pase/pieces/fantasy/
    - assets/images/images_pase/pieces/fresca/
    - assets/images/images_pase/pieces/governor/
    - assets/images/images_pase/pieces/kosal/
    - assets/images/images_pase/pieces/leipzig/
    - assets/images/images_pase/pieces/maestro/
    - assets/images/images_pase/pieces/mpchess/
    - assets/images/images_pase/pieces/pixel/
    - assets/images/images_pase/pieces/defecto/
    - assets/json/
    - assets/music/
    - assets/sfx/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/fonts/Permanent_Marker/PermanentMarker-Regular.ttf
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon-adaptive-foreground.png"
